# fly.toml app configuration file generated for hello-chatgpt-apps on 2025-10-11T16:04:40-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'noodleseed'
primary_region = 'sjc'

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8000"
  NODE_ENV = "production"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [[http_service.checks]]
    interval = "15s"
    timeout = "3s"
    grace_period = "5s"
    method = "GET"
    path = "/health"
    protocol = "http"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
